package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/elyseeMB/relay-compiler/graph/model"
)

// var authors = map[string]*model.Author{
//     "1": {ID: "1", Name: "Alice", Role: model.RoleAdmin},
// }

// CreateAuthor is the resolver for the createAuthor field.
func (r *mutationResolver) CreateAuthor(ctx context.Context, input model.NewAuthor) (*model.Author, error) {

	author := &model.Author{
		ID:   fmt.Sprintf("%d", len(r.Resolver.Authors)+1),
		Name: input.Name,
		Role: *input.Role,
	}
	r.Resolver.Authors = append(r.Resolver.Authors, author)
	return author, nil
}

// CreateArticle is the resolver for the createArticle field.
func (r *mutationResolver) CreateArticle(ctx context.Context, input model.NewArtcile) (*model.Article, error) {
	draft := input.Draft
	if draft == nil {
		d := false
		draft = &d
	}

	status := input.Status
	if status == nil {
		s := model.StatusPrivate
		status = &s
	}

	access := input.AccessLevel
	if access == nil {
		a := model.AccessLevelFree
		access = &a
	}

	var author *model.Author
	for _, a := range r.Resolver.Authors {
		if a.ID == input.AuthorID {
			author = a
			break
		}
	}

	if author == nil {
		return nil, fmt.Errorf("author with id %s not found", input.AuthorID)

	}

	article := &model.Article{
		ID:          fmt.Sprintf("%d", len(r.Resolver.Articles)+1),
		Title:       input.Title,
		Summary:     input.Summary,
		Body:        input.Body,
		AccessLevel: *input.AccessLevel,
		Status:      *input.Status,
		Draft:       *draft,
		Authors:     author,
	}

	r.Resolver.Articles = append(r.Resolver.Articles, article)
	return article, nil

}

// Authors is the resolver for the authors field.
func (r *queryResolver) Authors(ctx context.Context) ([]*model.Author, error) {
	return r.Resolver.Authors, nil
}

// Articles is the resolver for the articles field.
func (r *queryResolver) Articles(ctx context.Context) ([]*model.Article, error) {
	return r.Resolver.Articles, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
