package console_v1

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/elyseeMB/relay-compiler/pkg/server/api/console/v1/schema"
	"github.com/elyseeMB/relay-compiler/pkg/server/api/console/v1/types"
)

// CreateAuthor is the resolver for the createAuthor field.
func (r *mutationResolver) CreateAuthor(ctx context.Context, input types.NewAuthor) (*types.User, error) {
	panic(fmt.Errorf("not implemented: CreateAuthor - createAuthor"))
}

// CreateArticle is the resolver for the createArticle field.
func (r *mutationResolver) CreateArticle(ctx context.Context, input types.NewArtcile) (*types.Article, error) {
	panic(fmt.Errorf("not implemented: CreateArticle - createArticle"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*types.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Articles is the resolver for the articles field.
func (r *queryResolver) Articles(ctx context.Context) ([]*types.Article, error) {
	panic(fmt.Errorf("not implemented: Articles - articles"))
}

// Mutation returns schema.MutationResolver implementation.
func (r *Resolver) Mutation() schema.MutationResolver { return &mutationResolver{r} }

// Query returns schema.QueryResolver implementation.
func (r *Resolver) Query() schema.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
