// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Entity interface {
	IsEntity()
	GetID() string
}

type Article struct {
	ID          string      `json:"id"`
	Title       string      `json:"title"`
	Summary     *string     `json:"summary,omitempty"`
	Body        string      `json:"body"`
	AccessLevel AccessLevel `json:"accessLevel"`
	Status      Status      `json:"status"`
	Users       *User       `json:"users"`
	Draft       bool        `json:"draft"`
}

func (Article) IsEntity()          {}
func (this Article) GetID() string { return this.ID }

type Mutation struct {
}

type NewArtcile struct {
	AuthorID    string       `json:"authorId"`
	Title       string       `json:"title"`
	Summary     *string      `json:"summary,omitempty"`
	Body        string       `json:"body"`
	Draft       *bool        `json:"draft,omitempty"`
	Status      *Status      `json:"status,omitempty"`
	AccessLevel *AccessLevel `json:"accessLevel,omitempty"`
}

type Query struct {
}

type User struct {
	ID       string `json:"id"`
	Email    string `json:"Email"`
	FullName string `json:"fullName"`
	Role     Role   `json:"role"`
}

func (User) IsEntity()          {}
func (this User) GetID() string { return this.ID }

type NewAuthor struct {
	Name string `json:"name"`
	Role *Role  `json:"role,omitempty"`
}

type AccessLevel string

const (
	AccessLevelFree AccessLevel = "FREE"
	AccessLevelPaid AccessLevel = "PAID"
)

var AllAccessLevel = []AccessLevel{
	AccessLevelFree,
	AccessLevelPaid,
}

func (e AccessLevel) IsValid() bool {
	switch e {
	case AccessLevelFree, AccessLevelPaid:
		return true
	}
	return false
}

func (e AccessLevel) String() string {
	return string(e)
}

func (e *AccessLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccessLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccessLevel", str)
	}
	return nil
}

func (e AccessLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccessLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccessLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleAdmin    Role = "ADMIN"
	RoleCustomer Role = "CUSTOMER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleCustomer,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleCustomer:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Status string

const (
	StatusPrivate Status = "PRIVATE"
	StatusPublic  Status = "PUBLIC"
)

var AllStatus = []Status{
	StatusPrivate,
	StatusPublic,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusPrivate, StatusPublic:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Status) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Status) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
